name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: npm run build
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: 'sns-manager'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: 'dist/apps/sns-api'
