name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build:prod
      - run: | # Files need to be commited to deploy them to heroku
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add -f dist/apps && git commit -m 'Add deploy files'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: 'sns-manager'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
